#--- Packages to import
library(nasapower)
library(xts)
library(dplyr)
library(ggplot2)
library(gridExtra)
library(grid)
library(ggfortify)
library(ggsci)
library(scales)
library(RColorBrewer)
library(forecast)
library(tsbox)
library(lattice)
library(lubridate)
library(stats)
library(tidyr)
library(zoo)
